[build]
  publish = "public"
  command = "yarn build"

  [build.environment]
    YARN_VERSION = "1.3.2"
    YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "netlify-plugin-a11y"
[[plugins]]
package = netlify-plugin-search-index
[[plugins]]
package = "@netlify/plugin-sitemap"
[[plugins]]
package = "netlify-plugin-subfont"