version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.19.0
  working_directory: ~/practice-sh-blog-by-ak

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.lock" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.lock" }}

  # lint:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - dependencies-{{ checksum "yarn.lock" }}
  #     - run: yarn lint

  # test:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - dependencies-{{ checksum "yarn.lock" }}
  #     - run: yarn test --runInBand --no-cache

  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.lock" }}
      - run: npm install jest
      - run: npm tun test:coverage --runInBand --no-cache
      - save_cache:
          key: coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - coverage

  codecov:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.lock" }}
      - restore_cache:
          keys:
            - coverage-output-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install jest
      - run: npm install --global codecov
      - run: yarn codecov
    
workflows:
  version: 2
  test:
    jobs:
      - install
      # - lint:
      #     requires:
      #       - install
      # - test:
      #     requires:
      #       - install
      - coverage:
          requires:
            - install
      - codecov:
          requires:
            - coverage